version: '2'

services:
  web:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - "80:80"
    env_file:
      - ".env"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    volumes:
      - ../data/${NGINX_HOST}/www:/var/www
      - ../.conf/nginx/${PROJECT_TYPE}.conf:/etc/nginx/conf.d/default.conf
      - ../log/${NGINX_HOST}/nginx:/var/log/nginx
    links:
      - php

  php:
    container_name: php
    build: .
    restart: always
    env_file:
      - ".env"
    volumes:
      - ../data/${NGINX_HOST}/www:/var/www
      - ../.conf/.bashrc:/root/.bashrc
      - ../.conf/.bash_history:/root/.bash_history
      - ../.conf/composer-auth.json:/root/.composer/auth.json

  mysql:
    container_name: mysql
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ../data/${NGINX_HOST}/mysql:/var/lib/mysql
