version: '2'

services:
  web:
    container_name: ${PROJECT_TYPE}_nginx
    image: nginx
    restart: always
    ports:
      - "80:80"
    env_file:
      - ".env"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    volumes:
      - ../data/www/${NGINX_HOST}/html:/var/www/html
      - ../.conf/nginx/${PROJECT_TYPE}.conf:/etc/nginx/conf.d/default.conf
      - ../log/${NGINX_HOST}/nginx:/var/log/nginx
    links:
      - php
      - mysql

  workspace:
    container_name: ${PROJECT_TYPE}_workspace
    build: ./workspace
    env_file:
      - ".env"
    stdin_open: true
    tty: true
    volumes:
      - ../data/www/${NGINX_HOST}:/var/www
      - ../.conf/.bashrc:/root/.bashrc
      - ../.conf/.bash_history:/root/.bash_history
      - ../.conf/composer-auth.json:/root/.composer/auth.json

  php:
    container_name: ${PROJECT_TYPE}_php
    build: ./fpm
    restart: always
    env_file:
      - ".env"
    volumes:
      - ../data/www/${NGINX_HOST}/html:/var/www/html

  mysql:
    container_name: mysql
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ../data/mysql:/var/lib/mysql
